[workspace]
members = ["nabto_webrtc", "nabto_webrtc_perfect_negotiation"]
default-members = ["nabto_webrtc"]
resolver = "2"

[profile.release-size]
inherits = "release"
opt-level = "z"          # Optimize for size
lto = true               # Enable Link Time Optimization
codegen-units = 1        # Better optimization with single codegen unit
strip = true             # Strip symbols from binary
panic = "abort"          # Abort on panic (smaller binary)
